### ISSUE TITLE
Favorite Programming Language incorrect answer

### ISSUE THREAD

**Issue by AmirNaghibi** [noops-challenge/fizzbot#1]
The following request gives me an error:
`curl -X POST -d {"answer":"python"} https://api.noopschallenge.com/fizzbot/questions/1`

`{"message":"Please provide an answer that is a string.","result":"incorrect"}`

But I have followed the example response:
`"exampleResponse":{"answer":"COBOL"}`

What am I missing here?

**Comment by davidmfoley** [comment]
Try `curl -X POST -H "Content-Type: application/json" -d '{"answer":"python"}' https://api.noopschallenge.com/fizzbot/questions/1`

**Comment by AmirNaghibi** [comment]
Thanks, @davidmfoley. it works!!! 👍 I was missing the header part.
