### ISSUE TITLE
Unable to post question

### ISSUE THREAD

**Issue by moturi-phil** [noops-challenge/fizzbot#19]
![issue](https://user-images.githubusercontent.com/33871682/60251514-53060100-98d1-11e9-9aa2-a59ac35e6c50.png)
I can't get past {"answer" : "python" }

**Comment by doolittle** [comment]
Hi @ReckerPhildev what does the Fizzbot return when you post that object to the API?

**Comment by moturi-phil** [comment]
It doesn't return anything, I have to end the process myself, I have all the installation correctly, I don't understand where the problem might be coming from.

**Comment by Ri2parna** [comment]
Which language are you using, it seems it is ruby though. i can help if its in python.

**Comment by moturi-phil** [comment]
Okay thank you so much, I had some dependancy issue, it's what had caused the problem earlier
